DROP TABLE IF EXISTS `SCHEDULER_JOB_API_REST` CASCADE;

CREATE TABLE `SCHEDULER_JOB_API_REST`
(
	`SCHEDULER_JOB_API_REST_ID` INT NOT NULL AUTO_INCREMENT,
	`CODE` VARCHAR(50) NOT NULL,
	`ENDPOINT` VARCHAR(500) NOT NULL,
	`SCHEDULE` VARCHAR(100) NOT NULL,
	`STATUS` VARCHAR(2) NOT NULL,
	CONSTRAINT `PK_SCHEDULER_JOB_API_REST_ID` PRIMARY KEY (`SCHEDULER_JOB_API_REST_ID` ASC)
);

ALTER TABLE SCHEDULER_JOB_API_REST ADD CONSTRAINT UC_SCHEDULER_JOB_API_REST_CODE UNIQUE (CODE);

ALTER TABLE SCHEDULER_JOB_API_REST ADD CONSTRAINT CHK_SCHEDULER_JOB_API_REST_STATUS CHECK (STATUS IN ('AC', 'IN'));